### ISSUE TITLE
GPT2 example

### ISSUE THREAD

**Issue by j3nsykes** [runwayml/processing-library#11]
Is more recent updates Runway has changed the output text data.getString() to be "generated_text" not "text". This makes the Processing example work on versions around 0.10.10. 
However, in the more recent versions 0.10.27 this example fails to generate the output text in either Runway or Processing. It receives the input String fine which makes me think it isn't a port or network issue. Perhaps another message structure was changed that is not visible in the code but part of the library file? 
Other examples continue to work such as AttGAN.

**Comment by orgicus** [comment]
Thanks for pointing that out,

Indeed it looks like the json structure for the model changed a bit.

I'll need to do a pass of testing examples and updating them accordingly

**Comment by cvalenzuela** [comment]
We identified a bug in 0.10.27 that was causing an issue with the way data was proceeded when using the Networks panel. We are patching the bug and will update the fix in 0.10.28

**Comment by j3nsykes** [comment]
Amazing thank you!

**Comment by cvalenzuela** [comment]
This is now fixed on 0.10.28! @j3nsykes try updating your version of Runway.

Also, you might need to update the output to:

```java
 text_output = data.getString("generated_text");
```

Let me know if that works

**Comment by j3nsykes** [comment]
That works great now thanks!

**Comment by orgicus** [comment]
Closing this issue as it's been resolved by @j3nsykes in PR #12
