### ISSUE TITLE
support for hosted models

### ISSUE THREAD

**Issue by dattasaurabh82** [runwayml/processing-library#16]
**Will there be support for hosted models from runway in the processing library itself?**
Right now it just supports local instances over http.

The python code example with requests lib works smoothly. 
Although needed a bit of a cleanup, in the response section to, in order to parse the data for saving the image: 

**[python code example snippet for re-saving the response as an image]**
```
# Get the interested part from the response, containing base64 image data
img_str = output["image"]

# To remove "data:image/png;base64,..." from the response
print("\nClean Output:")
clean_img_str = img_str[img_str.index(',')+1:]

# For saving the image file
img_data = base64.b64decode(clean_img_str)
filename = 'your image.png'
with open(filename, 'wb') as f:
    f.write(img_data)
```
BTW, Great work. :+1: 

---------------------------------------------------------------

I was trying to use processing **http.requests** library to send a `post request` to `query` with a `base64 string data of an image` (_as the api only support data inputs as base64 string_).

Here's my snippet: 
```
import javax.xml.bind.DatatypeConverter;
import http.requests.*;
String model_end_point = "<API_ENDPOINT>/query";
String api_key = "<API_KEY>";

void setup() {
  size(1020, 480);
  background(25);

  // convert image to byte array
  byte imageByte[] = loadBytes("3.jpg");
 
  // prepare the base64 string from the byte array of the image 
  String b64 = DatatypeConverter.printBase64Binary(imageByte);
  // println("Original image base64 data:");
  // println(b64);
  // println("\n");

  PostRequest post = new PostRequest(model_end_point);
  post.addHeader("Accept", "application/json");
  post.addHeader("Content-Type", "application/json");
  post.addHeader("Authorization", api_key);
  post.addData("image", b64);
  post.send();

  println("\nResponse:");
  try{
    println(post.getContent());
  }catch (Exception e){
    println(e);
  }
  exit();
}
```

To this I always get an error response: 
`{"error":"Internal server error"}`

I do not know what I'm doing wrong. 🤔
**Note:** _I was referencing the python code example from the runway itself_. 

Any lead would help here.

**Comment by dattasaurabh82** [comment]
I was trying to use processing **http.requests** library to send a `post request` to `query` with a `base64 string data of an image` (_as the api only support data inputs as base64 string_).

Here's my snippet: 
```
import javax.xml.bind.DatatypeConverter;
import http.requests.*;
String model_end_point = "<API_ENDPOINT>/query";
String api_key = "<API_KEY>";

void setup() {
  size(1020, 480);
  background(25);

  // convert image to byte array
  byte imageByte[] = loadBytes("3.jpg");
 
  // prepare the base64 string from the byte array of the image 
  String b64 = DatatypeConverter.printBase64Binary(imageByte);
  // println("Original image base64 data:");
  // println(b64);
  // println("\n");

  PostRequest post = new PostRequest(model_end_point);
  post.addHeader("Accept", "application/json");
  post.addHeader("Content-Type", "application/json");
  post.addHeader("Authorization", api_key);
  post.addData("image", b64);
  post.send();

  println("\nResponse:");
  try{
    println(post.getContent());
  }catch (Exception e){
    println(e);
  }
  exit();
}
```

To this I always get an error response: 
`{"error":"Internal server error"}`

I do not know what I'm doing wrong. 🤔
**Note:** _I was referencing the python code example from the runway itself_. 

Any lead would help here.

**Comment by orgicus** [comment]
Hi @dattasaurabh82 

Apologies for the delayed response and thank you for the kind words.

Great to see you're connecting to RunwayML using Python.

It's hard to tell exactly what the issue is without seeing the Base64 encoded image and JSON payload and knowing what Model you're connecting to.
There are a few things that could go wrong , for example:
- the Base64 string not including the MIME type prefix (e.g. `data:image/jpeg;base64,`), 
- the JPG part accidentally including extra data/not 3 channels for some reason
- the JSON payload not using the right JSON schema for the Runway model you're trying to use, etc.

This part looks a bit funny: ` post.addData("image", b64);`
Based on the [jsonpost http.post example](https://github.com/runemadsen/HTTP-Requests-for-Processing/blob/master/examples/jsonpost/jsonpost.pde#L10) I would assume this to be the strigified JSON object (e.g. a stringified version of `{"image":"YOUR_B64_IMAGE_HERE"}`) (instead of an HTTP form with key "image").

Currently the library doesn't support hosted models, but hopefully I'll get a chance to fix this by the end of the month 😊😅🤞  

In the meantime you could try something like:
```processing
import javax.xml.bind.DatatypeConverter;
import com.runwayml.ModelUtils;
import http.requests.*;
String model_end_point = "<API_ENDPOINT>/query";
String api_key = "<API_KEY>";

void setup() {
  size(1020, 480);
  background(25);

  String runwayQuery = ModelUtils.toRunwayImageQuery(loadImage("3.jpg"));
  
  println(runwayQuery);
  
  PostRequest post = new PostRequest(model_end_point);
  post.addHeader("Accept", "application/json");
  post.addHeader("Content-Type", "application/json");
  post.addHeader("Authorization", api_key);
  post.addData(runwayQuery);
  post.send();

  println("\nResponse:");
  try{
    println(post.getContent());
  }catch (Exception e){
    println(e);
  }
  exit();
}
```

Note that the above code is not tested, so I can't guarantee it will run without a hitch,
however I hope it helps illustrate a path to a working solution.

Best of luck,
George

**Comment by dattasaurabh82** [comment]
@orgicus Thanks for the quick response (Common! It wasn't a delayed response 😇 and better late than never 🙃).  

> It's hard to tell exactly what the issue is without seeing the Base64 encoded image and JSON payload and knowing what Model you're connecting to.

The model that I'm connecting to is the [DeepLab's Semantic maps extractor based on objects from an image](https://app.runwayml.com/models/genekogan/DeepLab)

The first and the last assumptions of yours were correct. I tested them as below: 

**_Important Note for others, before we proceed further_**: The version that one gets by downloading the [http_requests library for processing](https://github.com/runemadsen/HTTP-Requests-for-Processing), either from the official releases page or the Processing's contribution manager, _[doesn't support posting stringified JSON data](https://github.com/runemadsen/HTTP-Requests-for-Processing/issues/34)_ as mentioned in the above suggestion: 
`post.addData("{"image":"YOUR_B64_IMAGE_HERE WITH PROPER MIME TYPE"}"); // will not work with the official version of library`

**_Solution for the aforementioned problem statement, before we proceed further_**: 
Use this [pre-release 0.15 version](https://github.com/runemadsen/HTTP-Requests-for-Processing/releases/tag/0.1.5.trial) of the [http_requests library for processing](https://github.com/runemadsen/HTTP-Requests-for-Processing), if, anywhere, you want to post `stringified json data` with the `addData("<string>")` method [ **Not directly relevant to this issue only ]

Okay now, @orgicus , yes the correct MIME type prefix (`data:image/jpeg;base64,`) was the first issue. 

So I checked and yes , these parts:
```
import com.runwayml.ModelUtils;
String runwayQuery = ModelUtils.toRunwayImageQuery(loadImage("3.jpg"));
```
returns the base64 data with the right MIME TYPE as prefix for the runway's server side.  
`println(runwayQuery);`
response:
`"{"image":"data:image/png;base64,<base 64 string>"` 
Which we can then feed to the post req. 
 

---------------------------------------------------------------

**Additional info:** 

If someone want's to make their life harder or just is curious and not use the runway's Processing lib (Not encouraging this action as it is a great one 😋) here's what to do, to replace the above two lines, which returns the same post req data. 

```
import javax.xml.bind.DatatypeConverter;
JSONObject json_payload;

// load the image and get the raw bytes
 byte imageByte[] = loadBytes("3.jpg");
// convert it into base 64 string:
String raw_b64 = DatatypeConverter.printBase64Binary(imageByte);
// add the correct MEME TYPE, manually expected by the Runway's remote server:
String corr_b64 = "data:image/jpeg;base64," + raw_b64;  
// ** You can generate the correct MEME type and make it as the string prefix above, by code as well .. --> stack_overflow

// now make the JSON object
json_payload = new JSONObject();
// create the json KEY VALUE pair for the data
json_payload.setString("image", corr_b64);

//... post req stuff as before ..
post.addData(json_payload.toString());
post.send();

//... rest of the code to get response
```

This also works 

----------------------------------------------

But @orgicus can't wait for the next version of the library which will natively support the hosted models as they are very nice for permanent installations and stuff.  🤓🙏🏽
