### ISSUE TITLE
Publish library to the Processing library page

### ISSUE THREAD

**Issue by cvalenzuela** [runwayml/processing-library#3]
Once we have our first release, we should be able to submit the library to the Processing library website and directory: https://processing.org/reference/libraries/

**Comment by shiffman** [comment]
Happy to help with this process!

**Comment by cvalenzuela** [comment]
@shiffman, we might be ready to start moving ahead with this process. What are the next steps?

**Comment by kllsamui** [comment]
meanwhile you are welcome to put some info 

> WOW we have a library update!!!

at the https://discourse.processing.org/

**Comment by orgicus** [comment]
@shiffman I've contacted Elie, the Processing Librarian, a few weeks ago but haven't heard back.
Suspecting he is very busy. If you manage to reach him, these are the relevant .txt and .zip links:

https://github.com/runwayml/processing-library/releases/download/latest/RunwayML.txt
https://github.com/runwayml/processing-library/releases/download/latest/RunwayML.zip

Thank you 🤗

**Comment by shiffman** [comment]
I see him sometimes at ITP so I will check in! Also tagging @prisonerjohn here in case a GitHub notification is helpful! Cannot wait to dig into this more and use it in some video tutorials!

**Comment by prisonerjohn** [comment]
Sorry I think I missed your note! I'll take a look at it ASAP
