### ISSUE TITLE
Supporting base64 encoding with PGraphics objects 

### ISSUE THREAD

**Issue by b2renger** [runwayml/processing-library#5]
It would be nice to be able to encode PGraphics object to a base64 image to be send to runway too (as it is already possible for PImage).

To be more clear here is what I have in mind :

`
PGraphics pg;
void setup(){
 pg = createGraphics(600,400);
}

void draw(){
  pg.beginDraw();
  pg.fill(255);
  pg.ellipse(mouseX,mouseY,25,25);
  pg.endDraw();
}

void keyPressed(){
  JSONObject input = new JSONObject();
  // set style image
  input.setString("style_image",ModelUtils.toBase64(styleImage));
  // set content image
  input.setString("content_image",ModelUtils.toBase64(pg));
  // set interpolation weight
  input.setFloat("interpolation_weight",interpolationWeight);
  // query Runway
  runway.query(input.format(-1));
}
`

**Comment by orgicus** [comment]
@b2renger You can already do that as `PGraphics` extends `PImage`, just call `get()` on the `PGraphics` instance to rasterise it:

```processing
input.setString("content_image",ModelUtils.toBase64(pg.get()));
```
Checkout the SPADE_COCO_Paint example in the HTTP folder, [line 21](https://github.com/runwayml/processing-library/blob/master/examples/HTTP/SPADE_COCO_Paint/Runway.pde#L21
) in particular

**Comment by b2renger** [comment]
Awesome thanks !

**Comment by b2renger** [comment]
@orgicus  I'm reopening the issue because even if it work with spade coco when I try to do the same thing with something like adaptative style transfer I get an error. 

Like the one below

```
java.lang.NullPointerException
	at com.runwayml.ModelUtils.fromBase64(Unknown Source)
	at AdaptiveStyleTransfer_watercolor.runwayDataEvent(AdaptiveStyleTransfer_watercolor.java:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.runwayml.Runway.dispatchData(Unknown Source)
	at com.runwayml.RunwayHTTP.sendQuery(Unknown Source)
	at com.runwayml.RunwayHTTP.query(Unknown Source)
	at AdaptiveStyleTransfer_watercolor.sendImageToRunway(AdaptiveStyleTransfer_watercolor.java:105)
	at AdaptiveStyleTransfer_watercolor.keyPressed(AdaptiveStyleTransfer_watercolor.java:98)
	at processing.core.PApplet.keyPressed(PApplet.java:3121)
	at processing.core.PApplet.handleKeyEvent(PApplet.java:2996)
	at processing.core.PApplet.dequeueEvents(PApplet.java:2648)
	at processing.core.PApplet.handleDraw(PApplet.java:2486)
	at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1547)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:313)
```

I am not sure what it actually means, I'll try to post a simple code example

**Comment by orgicus** [comment]
@b2renger Something looks off with what data gets passed to `fromBase64` on `keyPressed` in your sketch.

Can you please post a minimal code snippet of how you tried to do the call ?

(If it's possible to attach the sketch (or if it's a single .pde file paste in code markdown) that might help debug the issue)

**Comment by b2renger** [comment]
@orgicus here some code for you to try, it's basically adapted from your example 

```java

// import Runway library
import com.runwayml.*;
// reference to runway instance
RunwayHTTP runway;

PImage runwayResult;
String status = "";

PGraphics pg;
color h =0;
float cXPos = 0;


void setup() {
  // match sketch size to default model camera setup
  size(1280, 360);
  // setup Runway
  runway = new RunwayHTTP(this);
  // update manually
  runway.setAutoUpdate(false);

  colorMode(HSB, 360, 100, 100, 100);
  background(0, 0, 100);

  pg = createGraphics(640, 360);
  pg.beginDraw();
  pg.colorMode(HSB, 360, 100, 100, 100);
  pg.background(0);
  pg.endDraw();
}

void draw() {
  background(0);
  image(pg, 0, 0);

  for (int i = 0; i < width; i++) {
    float h = map(i, 0, width, 0, 360);
    stroke(h, 100, 100);
    line(i, 0, i, 20);
  }
  stroke(255);
  line(cXPos, 0, cXPos, 20);
}


void mouseDragged() {
  if (mouseY>20) {
    color c = color(h, 95, 70);
    float s = dist(pmouseX, pmouseY, mouseX, mouseY)*5+ 40;
    pg.beginDraw();
    pg.fill(c);
    pg.ellipse(mouseX, mouseY, s, s);
    pg.endDraw();
   
  } else {
    h = int(map(mouseX, 0, width, 0, 360));
    cXPos = mouseX;
  }
}


void keyPressed() {
  if (key == CODED && keyCode == LEFT) h = constrain(h-=5, 0, 360); 
  if (key == CODED && keyCode == RIGHT) h = constrain(h+=5, 0, 360);
  if (key == ' ') {
    status = "waiting for results";
    sendImageToRunway();
  }
}

void sendImageToRunway() {
  runway.query(pg.get(), ModelUtils.IMAGE_FORMAT_JPG, "contentImage");
}

// this is called when new Runway data is available
void runwayDataEvent(JSONObject runwayData) {
  // point the sketch data to the Runway incoming data 
  String base64ImageString = runwayData.getString("stylizedImage");
  // try to decode the image from
  try {
    runwayResult = ModelUtils.fromBase64(base64ImageString);
  }
  catch(Exception e) {
    e.printStackTrace();
  }
  status = "received runway result";
}

// this is called each time Processing connects to Runway
// Runway sends information about the current model
public void runwayInfoEvent(JSONObject info) {
  println(info);
}
// if anything goes wrong
public void runwayErrorEvent(String message) {
  println(message);
}
```

**Comment by orgicus** [comment]
@b2renger Thanks for the sharing that, super helpful !

Going through http://localhost:8000/data I spotted this message:
```javascript
{"error":"Error during inference: ValueError(\"Cannot feed value of shape (1, 360, 640, 4) for Tensor u'placeholder/photo:0', which has shape '(1, ?, ?, 3)'\",).","traceback":["File \"/miniconda/lib/python2.7/site-packages/runway/model.py\", line 135, in command_route\n    raise reraise(InferenceError, InferenceError(repr(err)), sys.exc_info()[2])","File \"/miniconda/lib/python2.7/site-packages/runway/model.py\", line 128, in command_route\n    results = command_fn(self.model, deserialized_inputs)","File \"server.py\", line 40, in stylize\n    img = model['sess'].run(model['output_photo'], feed_dict={model['input_photo']: img})","File \"/miniconda/lib/python2.7/site-packages/tensorflow/python/client/session.py\", line 929, in run\n    run_metadata_ptr)","File \"/miniconda/lib/python2.7/site-packages/tensorflow/python/client/session.py\", line 1128, in _run\n    str(subfeed_t.get_shape())))"]}
```

(@cvalenzuela I was expecting this to be in `/error`, not in `/data`, maybe this particular model is a bit different ?)

The  gist of the error: `Cannot feed value of shape (1, 360, 640, 4) for Tensor u'placeholder/photo:0', which has shape '(1, ?, ?, 3)'\",).` means image is 4 channel (`ARGB`  PImage with alpha channel) when this network expects a 3 channel image (RGB only)

ModelUtils at the moment simply adds the JPG or PNG mime type, but doesn't check the number of colour channels received.

One solution is to convert the transparent `PGraphics` to an opaque `PImage` using probably the least used [filter()](https://processing.org/reference/PImage_filter_.html): `OPAQUE`.
Try this:

```processing
void sendImageToRunway() {
  // get a PImage snapshot of the buffer
  PImage contentImage = pg.get();
  // make it opqaue (drop alpha channel)
  contentImage.filter(OPAQUE);
  // send opaque image to Adaptive-Style-Transfer
  runway.query(contentImage, ModelUtils.IMAGE_FORMAT_JPG, "contentImage");
}
```

**Comment by b2renger** [comment]
@orgicus That's great ! it works nicely :)

I guess dealing with several types of images won't be an easy task and might be hard for beginners.

Incidently when I export an image with [save()](https://processing.org/reference/save_.html)
```
pg.save("test.png");
```
The image gets saved as an ARGB image and in runway when I use the input from file with the same model it does manage to generate a new image. So is it the model ? does runway do something when getting an image from file that it doesn't do when receiving an image from http ?
